version: '3'

services:

  ### PostgreSQL ###########################################
  postgres:
    image: postgres:11
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  ### Workspace Utilities ##################################
  workspace:
    build:
      context: ./docker/containers/workspace
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ${CODE_PATH}:/var/www/application
    links:
      - postgres
    tty: true
    

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./docker/containers/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ${CODE_PATH}:/var/www/application
    expose:
      - "9000"
    links:
      - postgres
    

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./docker/containers/nginx
      args:
        - PUID=${PUID}
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ${CODE_PATH}:/var/www/application
      - ./docker/logs/server/nginx/:/var/log/nginx
      - ./docker/containers/nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
    links:
      - php-fpm
    

  ### Adminer #############################################
  adminer:
    image: clue/adminer
    ports:
      - "72:80"
    links:
      - postgres
    